// Generated by Selenium IDE

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
public class CompraSite {
  private WebDriver driver;
  
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void saucedemo() {
    driver.get("https://www.saucedemo.com/");
    driver.manage().window().setSize(new Dimension(1456, 876));
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-backpack\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"shopping-cart-link\"]")).click();
    assertEquals(driver.findElement(By.cssSelector("*[data-test=\"inventory-item-price\"]")).getText(),"$29.99");
    driver.findElement(By.cssSelector("*[data-test=\"checkout\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"firstName\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"firstName\"]")).sendKeys("Marcos");
    driver.findElement(By.cssSelector("*[data-test=\"lastName\"]")).sendKeys("Cardoso");
    driver.findElement(By.cssSelector("*[data-test=\"postalCode\"]")).sendKeys("17011240");
    driver.findElement(By.cssSelector("*[data-test=\"continue\"]")).click();
    assertEquals(driver.findElement(By.cssSelector("*[data-test=\"inventory-item-price\"]")).getText(), "$29.99");
    assertEquals(driver.findElement(By.cssSelector("*[data-test=\"total-label\"]")).getText(), "Total: $32.39");
    driver.findElement(By.cssSelector("*[data-test=\"finish\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"complete-header\"]")).click();
    assertEquals(driver.findElement(By.cssSelector("*[data-test=\"complete-header\"]")).getText(),
    "Thank you for your order!");
  }

}
  

